### PR TITLE
window sensor from develo

### PR DESCRIPTION
**Pull request by redxeagle**
Implemented a window sensor from devolo (should work with every window contact sensor)

### CODE REVIEW

**Comment by Timvdv** [comment]
Cool! I'll test & publish it right away.

I wonder one thing, how did you manage to pair the z-wave devices with that zwave-USB stick?

**Comment by redxeagle** [comment]
oh that is a "funny" story 
I bought a bundle for the "Pulse Station" home automation server, which could run on synology NAS.
But this plugin wasnt perfect because my hardrives doesnt want to go in hibernation anymore. The log file was written not in cache or memory. Always on these hardrives. But this software paired the usb stick together with the danfoss thermostat. But with this window sensor i really got trouble to pair it with the usb stick.  Finally pairing works well with open zwave control panel. https://github.com/OpenZWave/open-zwave-control-panel

But it was more try and error process to pair it and have a working combination instead of a workflow...

Hopefully i can reproduce it with another pair of window sensor and termostat later this year :)

**Comment by Timvdv** [comment]
Aah okay! Nice idea to use the zwave control panel. I'm planning to add discovery to the plugin in the future. It should be pretty easy.

I'm sure that it's possible to turn off logging by changing the variable to false. in z-wave-app protocol line 26. Just add `Logging: false,` at the next line. Hope that helps. (for more info look at: https://github.com/OpenZWave/node-openzwave-shared/blob/master/README-api.md)

At last: you forgot to add a few things (no problem! 😄) just look at my latest commits so you can add it next time! Your feature is live right now!

**Comment by redxeagle** [comment]
Yes true, had this change inside the config as well inside my config. didnt updated the github fork.

good that you seen this.

**Pull request merged**
